[package]
name = "rlgym-learn"
version = "2.0.0"
edition = "2024"
readme = "README.md"
license="Apache-2.0"

[lib]
name = "_rlgym_learn"
crate-type = ["cdylib"]

[dependencies]
bytemuck = "1.22.0"
enum-kinds = "0.5.1"
fastrand = "2.2.0"
indicatif = "0.18.6"
itertools = "0.13.0"
mio = { version = "1.2.2", features = ["net", "os-poll"] }
numpy = "0.29.0"
pyany-serde = "0.7.1"
pyo3 = { version = "0.29.0", features = ["py-clone"] }
raw_sync = "0.1.5"
rkyv = "0.8.10"
shared_memory = "0.12.4"
strum = "0.28.0"

[features]
rl = []
