[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "rlgym-learn"
description = "A generic framework for using learning algorithms with effecient parallelization of RLGym environments and an ergonomic API"
requires-python = ">=3.10,<=3.14"
authors = [
    { name = "Jonathan Keegan" }
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
# add version back to dynamic once out of alpha
version = "2.0.0a1"
dynamic = ["license", "readme"]
dependencies = [
    "rlgym>=2.0.0",
    "pydantic>=2.13.0",
    "typing_extensions>=4.15.0",
]

[project.optional-dependencies]
rl = [
    "rlgym[rl]>=2.0.0",
    "numpy>1.21"
]
tensor = [ "torch>1.13" ]

[tool.maturin]
python-source = "python"
module-name = "rlgym_learn._rlgym_learn"
bindings = 'pyo3'
features = ["rl"]

[tool.basedpyright]
reportExplicitAny = false
reportAny = false
reportMissingTypeStubs = false
reportMissingModuleSource = false
pythonVersion = "3.10"
